version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_container
    ports:
      - "8080:8080"
    volumes:
      - "jenkins_docker:/var/jenkins_home"
      - "./id_rsa:/var/jenkins_home/.ssh/id_rsa"
      - "./id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: always
volumes:
  jenkins_docker:
